export const ROLE_DEFS = {
  healthcare: {
    goals: [
      "Appointment bookings",
      "Lead form submissions",
      "Email list growth",
      "Course / program sales",
      "Speaking / consulting inquiries",
    ],
    pages: [
      "Home",
      "About",
      "Services",
      "Blog / Resources",
      "Speaking / Consulting",
      "Contact",
      "Patient Portal link",
      "Courses / Programs",
    ],
    goalsHeading: "9. Website Goals",
    pagesHeading: "10. Required Pages",
    integrationsHeading: "11. Integrations",
    complianceHeading: "12. Legal & Compliance",
    assetsHeading: "13. Asset & Brand Uploads",
    notesHeading: "14. Final Notes",
    bookingLabel: "Patient Booking (Jane, SimplePractice, etc.)",
    hipaaLabel: "HIPAA disclaimer needed?",
    hipaaShow: true,
    assetTitle: "Practice Photos",
    assetSubtitle: "Office and clinic environment",
  },
  tech: {
    goalsHeading: "Primary Website Goal",
    pagesHeading: "Required Pages",
    integrationsHeading: "Engagement & Integrations",
    complianceHeading: "SEO & Discoverability",
    assetsHeading: "Visual Assets",
    goals: [
      "Personal tech brand",
      "Startup or product credibility",
      "Hiring / recruiting",
      "Speaking / research visibility",
      "Consulting or advisory work",
    ],
    pages: [
      "Home",
      "About / Bio",
      "Products / Projects",
      "Research / Writing",
      "Speaking / Media",
      "Careers / Hiring",
      "Contact",
    ],
    bookingLabel: "Demo request or booking link",
    hipaaLabel: "Security / Privacy Policy",
    hipaaShow: false,
    assetTitle: "Product Visuals",
    assetSubtitle: "Screenshots, architecture diagrams, or team shots",
  },
  business: {
    goalsHeading: "Website Objective",
    pagesHeading: "Required Pages",
    integrationsHeading: "Conversion & Integrations",
    complianceHeading: "Contact Preferences",
    assetsHeading: "Brand Assets",
    goals: [
      "Attract consulting clients",
      "Build executive authority",
      "Secure speaking engagements",
      "Board or advisory opportunities",
    ],
    pages: [
      "Home",
      "Executive Bio",
      "Expertise / Services",
      "Case Studies / Impact",
      "Speaking / Media",
      "Insights / Articles",
      "Contact",
    ],
    bookingLabel: "Calendar booking (if any)",
    hipaaLabel: "NDA / Confidentiality",
    hipaaShow: false,
    assetTitle: "Professional Workspace",
    assetSubtitle: "Headshots, corporate environment",
  },
  impact: {
    goalsHeading: "Website Purpose",
    pagesHeading: "Required Pages",
    integrationsHeading: "Engagement Tools",
    complianceHeading: "Contact Preferences",
    assetsHeading: "Visual Assets",
    notesHeading: "Additional Notes",
    goals: [
      "Attract donors or funders",
      "Recruit volunteers",
      "Build public trust",
      "Share impact stories",
      "Support advocacy or campaigns",
    ],
    pages: [
      "Home",
      "About / Mission",
      "Programs",
      "Impact",
      "Get Involved",
      "Media / Press",
      "Contact",
    ],
    bookingLabel: "Donation Link",
    hipaaLabel: "Transparency Statement",
    hipaaShow: false,
    assetTitle: "Mission in Action",
    assetSubtitle: "Field work or community shots",
  },
  speaker: {
    goalsHeading: "Website Goals",
    pagesHeading: "Required Pages",
    integrationsHeading: "Integrations & Tech",
    complianceHeading: "Contact Preferences",
    assetsHeading: "Brand Assets",
    goals: [
      "Book discovery calls",
      "Sell coaching programs",
      "Attract speaking engagements",
      "Build authority & personal brand",
    ],
    pages: [
      "Home",
      "About",
      "Coaching / Programs",
      "Speaking",
      "Testimonials",
      "Resources / Blog",
      "Contact",
    ],
    bookingLabel: "Booking tool (Calendly, etc.)",
    hipaaLabel: "Coaching Agreement",
    hipaaShow: false,
    assetTitle: "Action Photos",
    assetSubtitle: "You on stage or presenting",
  },
  research: {
    goalsHeading: "Website Purpose",
    pagesHeading: "Required Pages",
    integrationsHeading: "Profiles & Contact",
    complianceHeading: "Contact Preferences",
    assetsHeading: "Content & Materials",
    goals: [
      "Showcase research & publications",
      "Support academic credibility",
      "Attract speaking / consulting",
      "Share public scholarship",
      "Promote books or courses",
    ],
    pages: [
      "Home",
      "About",
      "Research / Publications",
      "Books",
      "Teaching",
      "Media / Press",
      "Blog / Insights",
      "Contact",
    ],
    bookingLabel: "Academic Profile Link (ORCID, etc.)",
    hipaaLabel: "Research Ethics Statement",
    hipaaShow: false,
    assetTitle: "Research Materials",
    assetSubtitle: "PDFs, Charts, Books",
  },
};
