export const ROLE_DEFS = {
  healthcare: {
    audienceTitle: "3. Ideal Audience (SEO Gold)",
    audienceDesc:
      "Describe who you help best. This helps us write better copy for your site.",
    audienceQuestion: "Who do you primarily serve?",
    audienceOptions: [
      "Adults",
      "Children",
      "Teens",
      "Families",
      "Corporate",
      "Other",
    ],
    problemLabel: "Top Problem Your Patients Face",
    problemPlaceholder:
      "e.g. Chronic anxiety, recovery from sports injuries, etc.",
    nicheLabel: "Any niche focus?",
    nichePlaceholder: "e.g. insomnia, trauma, ADHD, fertility, pain",
    voiceHeading: "4. Brand Voice & Style",
  },
  tech: {
    audienceTitle: "Personal Brand Direction",
    audienceDesc: "How should you be perceived?",
    audienceQuestion: "Brand Persona",
    audienceOptions: [
      "Tech visionary",
      "Builder / Engineer",
      "Product strategist",
      "Research authority",
      "Startup founder",
    ],
    problemLabel: "Core expertise",
    problemPlaceholder: "e.g. full-stack, AI models, infra, product strategy",
    nicheLabel: "Primary technologies / stacks",
    nichePlaceholder: "e.g. React, Python, AWS, PyTorch",
  },
  business: {
    audienceTitle: "Personal Brand Direction",
    audienceDesc: "How do you want to be positioned online?",
    audienceQuestion: "Positioning Goal",
    audienceOptions: [
      "Visionary leader",
      "Strategic operator",
      "Industry authority",
      "Trusted advisor",
    ],
    problemLabel: "Strategic problems you solve",
    problemPlaceholder:
      "e.g. Operational inefficiency, lack of market strategy, etc.",
    nicheLabel: "Industries you specialize in",
    nichePlaceholder: "e.g. FinTech, Manufacturing, SaaS",
  },
  impact: {
    audienceTitle: "Mission & Cause",
    audienceDesc: "Define your core mission and the communities you serve.",
    audienceQuestion: "Communities or groups you serve",
    audienceOptions: [
      "Youth",
      "Women",
      "Refugees",
      "Environment",
      "Education",
      "Healthcare",
    ],
    problemLabel: "One-line mission statement",
    problemPlaceholder:
      "e.g. Empowering underserved communities through education.",
    nicheLabel: "Primary cause(s) you work on",
    nichePlaceholder: "e.g. Climate action, poverty alleviation, human rights",
    voiceHeading: "Visual Identity",
  },
  speaker: {
    audienceTitle: "Niche & Audience",
    audienceDesc: "Who is your ideal client or audience?",
    audienceQuestion: "Ideal audience",
    audienceOptions: [
      "Individuals",
      "Teams",
      "Founders",
      "Leaders",
      "Executives",
      "Corporations",
    ],
    problemLabel: "Key Challenge You Solve",
    problemPlaceholder: "e.g. Burnout, lack of clarity, scaling issues",
    nicheLabel: "Primary coaching niche",
    nichePlaceholder:
      "e.g. Life coaching, executive leadership, sales training",
  },
  research: {
    audienceTitle: "Research & Writing Focus",
    audienceDesc: "Define the scope and impact of your work.",
    audienceQuestion: "Who your work serves",
    audienceOptions: [
      "Academia",
      "Industry",
      "Policy Makers",
      "General Public",
      "Students",
      "Media",
    ],
    problemLabel: "Problems or questions your work addresses",
    problemPlaceholder: "e.g. How climate change affects urban migration...",
    nicheLabel: "Core themes you work on",
    nichePlaceholder: "e.g. AI Ethics, Sustainable Energy, Modern History",
  },
};
