export const ROLE_DEFS = {
  healthcare: {
    aboutHeading: "5. About You",
    authorityHeading: "6. Credentials & Authority",
    servicesHeading: "7. Services Offered",
    testimonialsHeading: "8. Testimonials & Social Proof",
    certLabel: "Certifications / Licenses",
    certPlaceholder: "e.g. State Medical License #12345",
    membershipLabel: "Memberships (AASM, APA, etc.)",
    membershipPlaceholder: "e.g. APA, AASM, AMA",
    servicePlaceholder: "e.g. Individual Therapy",
    testimonialPermission: "Permission received from patient",
    testimonialTitle: "e.g. Patient",
    deliveryOptions: ["In-person", "Virtual", "Hybrid"],
    ctaOptions: ["Book Appointment", "Contact Us", "Learn More"],
  },
  tech: {
    aboutHeading: "Innovation & Impact",
    authorityHeading: "Authority Signals",
    servicesHeading: "Products & Projects",
    testimonialsHeading: "Technical Proof",
    certLabel: "Patents / Novel Approaches",
    certPlaceholder: "e.g. US Patent 12,345,678",
    membershipLabel: "Open Source / Technical Groups",
    membershipPlaceholder: "e.g. Kubernetes Contributor, IEEE",
    servicePlaceholder: "e.g. Custom LLM Framework",
    testimonialPermission: "Permission received from peer or lead",
    testimonialTitle: "e.g. CTO, Senior Engineer",
    deliveryOptions: [
      "B2B SaaS",
      "Consumer App",
      "Technical Infrastructure",
      "Open Source Project",
      "Research Paper",
    ],
    ctaOptions: ["View Demo", "See GitHub", "Read Documentation"],
  },
  business: {
    aboutHeading: "Expertise & Impact",
    authorityHeading: "Authority Signals",
    servicesHeading: "Core Consulting Areas",
    testimonialsHeading: "Endorsements",
    certLabel: "Board Roles / Advisory",
    certPlaceholder: "e.g. Board Member at Acme Corp",
    membershipLabel: "Media Mentions",
    membershipPlaceholder: "e.g. WSJ, CNCB",
    servicePlaceholder: "e.g. Strategic Planning",
    testimonialPermission: "Permission received from peer/client",
    testimonialTitle: "e.g. Board Member",
    deliveryOptions: ["Consulting", "Advisory", "Interim Role", "Speaking"],
    ctaOptions: ["Book Consultation", "Contact Me", "View Profile"],
  },
  impact: {
    aboutHeading: "Programs & Initiatives",
    authorityHeading: "Partnerships & Recognition",
    servicesHeading: "Measurable Impact",
    testimonialsHeading: "Impact Stories",
    certLabel: "Partner Organizations",
    certPlaceholder: "e.g. Red Cross, UNICEF, local NGOs",
    membershipLabel: "Grants or Funding",
    membershipPlaceholder: "e.g. Ford Foundation, USAID",
    servicePlaceholder: "e.g. Education Program",
    testimonialPermission: "Permission received from beneficiary",
    testimonialTitle: "e.g. Community Member",
    deliveryOptions: ["Local", "National", "International"],
    ctaOptions: ["Donate", "Volunteer", "Learn More"],
  },
  speaker: {
    aboutHeading: "Signature Topics & Results",
    authorityHeading: "Credentials & Background",
    servicesHeading: "Coaching / Training Offers",
    testimonialsHeading: "Social Proof",
    certLabel: "Certifications",
    certPlaceholder: "e.g. ICF PCC, CPTD",
    membershipLabel: "Professional Affiliations",
    membershipPlaceholder: "e.g. Forbes Coaches Council, NSA",
    servicePlaceholder: "e.g. Executive Presence Workshop",
    testimonialPermission: "Permission received from client",
    testimonialTitle: "e.g. CEO, Event Organizer",
    deliveryOptions: [
      "1:1 coaching",
      "Group coaching",
      "Workshops",
      "Corporate training",
      "Speaking engagements",
    ],
    ctaOptions: ["Book a Call", "Join Waitlist", "Buy Now"],
  },
  research: {
    aboutHeading: "Ongoing Work",
    authorityHeading: "Media & Recognition",
    servicesHeading: "Publications & Teaching",
    testimonialsHeading: "Reviews & Impact",
    certLabel: "Certifications / Fellowships",
    certPlaceholder: "e.g. Fulbright Scholar, PMP",
    membershipLabel: "Academic Appointments",
    membershipPlaceholder: "e.g. Senior Fellow at Brookings",
    servicePlaceholder: "e.g. Book: 'The Future of AI'",
    testimonialPermission: "Permission received from source",
    testimonialTitle: "e.g. Colleague, Reviewer",
    deliveryOptions: [
      "Book",
      "Journal Article",
      "Report / Whitepaper",
      "Course",
      "Keynote / Lecture",
    ],
    ctaOptions: ["Read More", "Buy Book", "Download", "Enroll"],
  },
};
