export const ROLE_DEFS = {
  healthcare: {
    title: "Practice & Brand Foundation",
    practiceLabel: "Practice / Brand Name *",
    practicePlaceholder: "e.g. Zenith Health Care",
    nameLabel: "Practitioner Full Name *",
    namePlaceholder: "e.g. Dr. Saif Ullah",
    specialtyLabel: "Specialty / Focus Area",
    specialtyOptions: [
      "Mental & Behavioral Health",
      "Medical & Clinical",
      "Wellness & Health Coaches",
      "Holistic & Alternative",
    ],
    typeLabel: "Practice Type",
    typeOptions: [
      "Private Practice",
      "Group Practice",
      "Online Only",
      "Hybrid",
    ],
    basicHeading: "1. Basic Practice Info",
    contactHeading: "2. Contact & Locations",
    addressLabel: 'Practice Address (or "Telehealth Only")',
    addressIcon: "MapPin",
    experienceLabel: "Credentials (MD, PhD, LCSW, etc.)",
    experiencePlaceholder: "e.g. MD, PhD",
    emailPlaceholder: "Where should patient inquiries go?",
    typeField: "practice_type",
  },
  tech: {
    title: "Identity, Role & Tech Positioning",
    basicHeading: "Professional Identity",
    contactHeading: "Technical Focus",
    practiceLabel: "Company / Startup / Lab name",
    practicePlaceholder: "e.g. Nexa AI",
    nameLabel: "Full name *",
    namePlaceholder: "e.g. Sarah Chen",
    specialtyLabel: "Primary role",
    specialtyOptions: [
      "Founder / Co-Founder",
      "CTO / VP Engineering",
      "Product Manager",
      "Software Developer",
      "AI / ML Engineer",
      "Research Scientist",
      "Tech Consultant",
    ],
    typeLabel: "Years of experience in tech",
    typeOptions: ["0-2 years", "3-5 years", "5-10 years", "10+ years"],
    addressLabel: "Industry or domain (e.g. SaaS, AI)",
    addressIcon: "Globe",
    experienceLabel: "Technical Background / Expertise",
    experiencePlaceholder: "Brief summary of tech stack or roles...",
    emailPlaceholder: "Where should business inquiries go?",
    typeField: "years_experience",
  },
  business: {
    title: "Executive Identity & Positioning",
    basicHeading: "Executive Profile",
    contactHeading: "Leadership Scope",
    practiceLabel: "Company / Firm name",
    practicePlaceholder: "e.g. Acme Corp",
    nameLabel: "Full name *",
    namePlaceholder: "e.g. Marcus Sterling",
    specialtyLabel: "Current title",
    specialtyOptions: [
      "CEO",
      "Founder",
      "Managing Partner",
      "Consultant",
      "Advisor",
      "Board Member",
    ],
    typeLabel: "Organization size",
    typeOptions: [
      "Startup (<50)",
      "Mid-Market (50-500)",
      "Enterprise (500+)",
      "Fortune 500",
    ],
    addressLabel: "Markets served (Local/Global)",
    addressIcon: "Globe",
    experienceLabel: "Leadership Milestones",
    experiencePlaceholder: "Key roles or board positions held...",
    emailPlaceholder: "Where should inquiries go?",
    typeField: "practice_type",
  },
  impact: {
    title: "Identity & Mission",
    basicHeading: "Leader Identity",
    contactHeading: "Contact & Location",
    practiceLabel: "Organization name (if any)",
    practicePlaceholder: "e.g. Global Green Initiative",
    nameLabel: "Full Name *",
    namePlaceholder: "e.g. Elena Rodriguez",
    specialtyLabel: "Role",
    specialtyOptions: [
      "Nonprofit Founder",
      "Community Organizer",
      "Humanitarian Advocate",
      "Social Entrepreneur",
      "Political Professional",
    ],
    typeLabel: "Years in Impact Work",
    typeOptions: ["0-2 years", "3-5 years", "5-10 years", "10+ years"],
    addressLabel: "Home Base / Impact Region",
    addressIcon: "MapPin",
    experienceLabel: "Relevant Experience / Roles",
    experiencePlaceholder: "Describe your background in impact work...",
    emailPlaceholder: "Where should outreach inquiries go?",
    typeField: "years_experience",
  },
  speaker: {
    title: "Identity & Positioning",
    basicHeading: "Professional Identity",
    contactHeading: "Contact & Geography",
    practiceLabel: "Brand name (if any)",
    practicePlaceholder: "e.g. Elevate Coaching",
    nameLabel: "Full name *",
    namePlaceholder: "e.g. John Maxwell",
    specialtyLabel: "Professional title",
    specialtyOptions: [
      "Life Coach",
      "Leadership Coach",
      "Executive Coach",
      "Mentor",
      "Public Speaker",
    ],
    typeLabel: "Years of experience",
    typeOptions: ["0-2 years", "3-5 years", "5-10 years", "10+ years"],
    addressLabel: "Geographic focus",
    addressIcon: "Globe",
    experienceLabel: "Coaching / Speaking Experience",
    experiencePlaceholder: "Summary of your background...",
    emailPlaceholder: "Where should booking inquiries go?",
    typeField: "years_experience",
  },
  research: {
    title: "Identity, Position & Credentials",
    basicHeading: "Professional Identity",
    contactHeading: "Contact & Location",
    practiceLabel: "Institution / Organization (if applicable)",
    practicePlaceholder: "e.g. University of Toronto, The Brookings Inst.",
    nameLabel: "Full name *",
    namePlaceholder: "e.g. Dr. Ada Lovelace",
    specialtyLabel: "Professional title",
    specialtyOptions: [
      "Author",
      "Professor",
      "Researcher",
      "Industry Scholar",
      "Academic Consultant",
    ],
    typeLabel: "Years of experience",
    typeOptions: ["0-2 years", "3-5 years", "5-10 years", "10+ years"],
    addressLabel: "City / Institution Location",
    addressIcon: "MapPin",
    experienceLabel: "Academic & Professional Credentials",
    experiencePlaceholder: "Highest degrees, fellowships, etc.",
    emailPlaceholder: "Where should inquiries go?",
    typeField: "years_experience",
  },
};
